version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml"]
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    networks: [monitor-net]

  grafana:
    image: grafana/grafana
    ports: ["3001:3000"]
    environment: [GF_SECURITY_ADMIN_PASSWORD=admin123]
    volumes: ["grafana-storage:/var/lib/grafana"]
    networks: [monitor-net]

  node-exporter:
    image: prom/node-exporter
    ports: ["9100:9100"]
    volumes: ["/proc:/host/proc:ro", "/sys:/host/sys:ro", "/:/rootfs:ro"]
    command: [
      "--path.procfs=/host/proc",
      "--path.sysfs=/host/sys",
      "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    ]
    networks: [monitor-net]

networks:
  monitor-net:
    driver: bridge

volumes:
  grafana-storage:
