apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptocurrency-gaming-website
  namespace: cryptocurrency-gaming-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptocurrency-gaming-website
  template:
    metadata:
      labels:
        app: cryptocurrency-gaming-website
    spec:
      containers:
        - name: cryptocurrency-gaming-website
          image: sholly333/cryptocurrency-gaming-website:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cryptocurrency-gaming-website-service
  namespace: cryptocurrency-gaming-website
spec:
  selector:
    app: cryptocurrency-gaming-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
